blank_issues_enabled: false
contact_links:
  - name: Don't open issues on this repo
    url: https://github.com/withcatai/file-assets
    about: This is repo is for CatAI use only, don't open issues here
